# Development docker-compose file
version: '2.2'
services:
  www:
    build: .
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.join-group-dla-www.rule=Host(`join-group.dimonalovesanimals.org`)"
      - "traefik.http.routers.join-group-dla-www.entrypoints=websecure"
      - "traefik.http.routers.join-group-dla-www.tls.certresolver=myresolver"
